baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "MD/PhD Association for Clincial Research Outcomes"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = false      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
# NFB to do svg image in W3
#    mobile = "images/logo/logo-mobile.svg"
#    mobile_height = "36px"
#    desktop = "images/logo/logo.svg"
#    desktop_height = "36px"
    alt = "MD/PhD Association for Clincial Research Outcomes"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#1A4D93"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@uncmacro"
    meta_twitter_creator = "@uncmacro"
    meta_og_image = ""

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Promoting reproducible and representative research'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Getting Started"
    url = "/services/"
    weight = 1

  [[menu.main]]
    name = "Members"
    url = "/team/"
    weight = 2
  
  # [[menu.main]]
  #   name = "News"
  #   url = "/news/"
  #   weight = 3
  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
  # [[menu.footer]]
  #   name = "Home"
  #   url = "/"
  #   weight = 1
  #
  # [[menu.footer]]
  #   name = "Contact"
  #   url = "/contact/"
  #   weight = 2
